### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by nicejava** [TAdeJong/figures-imaging-moire-deformations#1]
I need find displacement from Sampling Moiré Method for Accurate Small Deformation
Distribution Measurement ..like this 
[https://www.youtube.com/watch?v=QUWitAk1md8 ](url)
you have example code ? .. thank you

**Comment by TAdeJong** [comment]
It is not very clear what you mean, but this is definitely not the right place from what I gather.
I suggest you take a look at scikit-image optical flow: https://scikit-image.org/docs/stable/auto_examples/registration/plot_opticalflow.html 
If you indeed need to gauge the displacement of an underlying lattice from the moire pattern (something not shown in the video), start with the reference here: https://github.com/TAdeJong/pyGPA/?tab=readme-ov-file#see-also and have a look at that repository in general, and in particular the notebook here: https://github.com/TAdeJong/pyGPA/blob/main/docs/GPA-accuracy_showcase.ipynb.

**Comment by nicejava** [comment]
Thank you for response ..
I need example code from this

![image](https://github.com/TAdeJong/figures-imaging-moire-deformations/assets/6760497/baaf58a8-4336-458c-a1ed-afcfad604067)

**I need calculate difference phase (equation 4. ).**
it's displacements. please solved code from this paper
I don't known what mean each variables in the equation how to write code python

**I need example code python  equation 1-4** ..  thank you very much
